# Generated by Django 4.0.3 on 2022-05-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='idCard_pic',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='id card image'),
        ),
        migrations.AddField(
            model_name='employee',
            name='membership',
            field=models.BooleanField(null=True),
        ),
    ]
