# Generated by Django 4.0.3 on 2022-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_employee_idcard_pic_employee_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='membership',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
