# Generated by Django 4.0.3 on 2022-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_employeemembership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
