# Generated by Django 4.0.3 on 2022-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_employeemembership_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemembership',
            name='membership_expiry',
            field=models.DateField(editable=False, null=True),
        ),
    ]
