# Generated by Django 4.0.3 on 2022-05-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_employeemembership_membership_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemembership',
            name='membership_expiry',
        ),
    ]
